### ISSUE TITLE
pandas.sample - error on interaction b/w batch_size and sample

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#347]
Running:
batch_size: 500
wrangles:
  - pandas.sample:
      parameters: 
        n: 100

Getting this error:
Error: Prep for Research
ValueError: pandas.sample - Cannot take a larger sample than population when 'replace=False'

**Comment by ebhills** [comment]
What's really weird is that it successfully creates the sheet (using excel.sheet)!

**Comment by ebhills** [comment]
Detail
Traceback (most recent call last):

File "/var/lang/lib/python3.10/site-packages/wrangles/recipe.py", line 402, in _execute_wrangles

df[params['output']] = getattr(df[params['input']], wrangle.split('.')[1])(**params.get('parameters', {}))

KeyError: 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/var/lang/lib/python3.10/site-packages/wrangles/recipe.py", line 404, in _execute_wrangles

df = getattr(df, wrangle.split('.')[1])(**params.get('parameters', {}))

File "/var/lang/lib/python3.10/site-packages/pandas/core/generic.py", line 6029, in sample

sampled_indices = sample.sample(obj_len, size, replace, weights, rs)

File "/var/lang/lib/python3.10/site-packages/pandas/core/sample.py", line 152, in sample

return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(

File "numpy/random/mtrand.pyx", line 1000, in numpy.random.mtrand.RandomState.choice

ValueError: Cannot take a larger sample than population when 'replace=False'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/var/task/app.py", line 108, in main_runner

df = wrangles.recipe.run(

File "/var/lang/lib/python3.10/site-packages/wrangles/recipe.py", line 774, in run

return future.result(timeout)

File "/var/lang/lib/python3.10/concurrent/futures/_base.py", line 458, in result

return self.__get_result()

File "/var/lang/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result

raise self._exception

File "/var/lang/lib/python3.10/concurrent/futures/thread.py", line 58, in run

result = self.fn(*self.args, **self.kwargs)

File "/var/lang/lib/python3.10/site-packages/wrangles/recipe.py", line 720, in _run_thread

df = _execute_wrangles(df, recipe['wrangles'], functions)

File "/var/lang/lib/python3.10/site-packages/wrangles/recipe.py", line 575, in _execute_wrangles

raise e.__class__(f"{wrangle} - {e}").with_traceback(e.__traceback__)

File "/var/lang/lib/python3.10/site-packages/wrangles/recipe.py", line 404, in _execute_wrangles

df = getattr(df, wrangle.split('.')[1])(**params.get('parameters', {}))

File "/var/lang/lib/python3.10/site-packages/pandas/core/generic.py", line 6029, in sample

sampled_indices = sample.sample(obj_len, size, replace, weights, rs)

File "/var/lang/lib/python3.10/site-packages/pandas/core/sample.py", line 152, in sample

return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(

File "numpy/random/mtrand.pyx", line 1000, in numpy.random.mtrand.RandomState.choice

ValueError: pandas.sample - Cannot take a larger sample than population when 'replace=False'

**Comment by ChrisWRWX** [comment]
How many rows are you running with this? Is there a batch that will be below 100 when split into 500? E.g. 550 rows -> 500, 50. You'd get that error when it did the 50.

**Comment by ebhills** [comment]
Hmm. Yes. For now, how do I get 50 random rows out of the 501 without getting that error?

**Comment by ChrisWRWX** [comment]
Just increase the batch_size so it includes every row. The 500 technically includes the header in the first batch at present, which I intend to change at some point. Anything over 501 should work.

**Comment by ebhills** [comment]
Got it - thanks!
